"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { configureBoneyard } from 'boneyard-js/react'

configureBoneyard({"color":"#e5e5e5","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110})
