"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _credit_cards_grid from './credit-cards-grid.bones.json'

configureBoneyard({"color":"#e5e5e5","darkColor":"#2a2a2a","animate":"shimmer","shimmerColor":"#ebebeb","darkShimmerColor":"#333333","speed":"2s","shimmerAngle":110})

registerBones({
  "credit-cards-grid": _credit_cards_grid,
})
